[CMOB - 2387] Details Refactor
DavitTsiskarashvili/Movies pull request #13
Opened 2023-08-08 16:01 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-2387

In this PR:
- Added separate API for movie details
- Added new DTO, mappers, use case and viewModel logic for fetching details data from API
- Added duration view in the xml file

2023-08-09 08:55 UTC, Gio481 requested changes

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/data/local/di/MapperModule.kt
> +    single {  }
ცარიელია

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/data/local/entity/FavouriteMovieEntity.kt
> +    val runtime: String,
რანთაიმ რას გულისხმობს, ცოტა გაუგებარია

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/data/mapper/dto/MovieDetailsDTOMapper.kt
> +                genreString = genres?.getOrNull(0)?.name ?: ""
genreString = genres?.getOrNull(0)?.name ?: "" ეს ხო მხოლოდ პირველ ჟანრს წამოიღებს

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/data/remote/service/api/ServiceApi.kt
> +    @GET(PREFIX+DETAILS)
ეს ცუდია, ჩვეულებრივ დააწერე

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/domain/model/MovieDomainModel.kt
> +    fun getFormattedRuntime(): String = runtime?.toHoursAndMinutes() ?: ""
რან თაიმს სახელი შეუცვალე

2023-08-09 08:55 UTC, Gio481 commented on app/src/main/java/com/movies/presentation/details/ui/DetailsFragment.kt
> +
ინტერფეის სეგრეგეიშენი რას გულისხმობს

2023-08-09 11:57 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/data/local/di/MapperModule.kt
> +    single {  }
ჩავამატე

2023-08-09 11:58 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/data/local/entity/FavouriteMovieEntity.kt
> +    val runtime: String,
duration გადავარქვი ზოგადად და აქედან საერთოდ ამოვშალე, არ არის ბაზაში საჭირო

2023-08-09 11:59 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/data/mapper/dto/MovieDetailsDTOMapper.kt
> +                genreString = genres?.getOrNull(0)?.name ?: ""
კი, მხოლოდ პირველი მჭირდება დასასეტად

2023-08-09 12:00 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/data/remote/service/api/ServiceApi.kt
> +    @GET(PREFIX+DETAILS)
done

2023-08-09 12:02 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/domain/model/MovieDomainModel.kt
> +    fun getFormattedRuntime(): String = runtime?.toHoursAndMinutes() ?: ""
done

2023-08-09 12:03 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/presentation/details/ui/DetailsFragment.kt
> +
ეს არ არის დასრულებული, თუმცა ცალკე ბრენჩზე დავიწყე ამის გადაკეთება ამიტომ ახალ პრ-ს რომ გამოვუშვებ იქ იქნება გასწორებული

2023-08-14 08:59 UTC, Gio481 approved these changes

2023-08-15 14:55 UTC, bchmsl approved these changes

2023-08-18 09:04 UTC, etozheluka approved these changes

2023-08-18 11:17 UTC, AnaRusadze approved these changes

2023-08-18 11:17 UTC, merged