[CMOB - 2172] Search
DavitTsiskarashvili/Movies pull request #5
Opened 2023-07-20 08:32 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-2172

In this PR added search functionality

2023-07-20 10:29 UTC, AleksandreGalogreBaramidze approved these changes

2023-07-26 10:00 UTC, AnaRusadze requested changes

2023-07-26 10:00 UTC, AnaRusadze commented on app/src/main/java/com/movies/data/remote/mapper/MovieListDTOMapper.kt
> +
მაპერში არ უნდა ეწეროს ფორმატის ექსთენშენი, მაპერის პასუხისმგებლობაა მხოლოდ დტოდან დომეინის გადამეპვა. ჯობია თვითონ დომეინ დატა კლასში შექმნა ფუნქციები და დამრგვალების ან პოსტერის ფუნქციები მანდ დაწერო

2023-07-26 10:00 UTC, AnaRusadze commented on app/src/main/java/com/movies/presentation/home/custom_view/SearchAndFilterView.kt
> +        if (binding.searchEditText.text?.isEmpty() == true){
isNullOrEmpty ხო არ ჯობია?

2023-07-26 10:00 UTC, AnaRusadze commented on app/src/main/java/com/movies/presentation/home/custom_view/SearchAndFilterView.kt
> +        }
params.endToStart  = if (isFilterVisible) binding.filterToggleButton.id else binding.cancelTextView.id

2023-07-26 10:00 UTC, AnaRusadze commented on app/src/main/java/com/movies/presentation/home/ui/HomeFragment.kt
> +                handleData(true)
handleData - false პარამეტრით არ გაქვს ხო გამოყენებული, როგორც მივხვდი? იქნებ ზედმეტი ბულიანია?

2023-07-26 10:00 UTC, AnaRusadze commented on app/src/main/res/layout/error_custom_view.xml
>          android:layout_marginTop="@dimen/dimen_110_dp"
android:layout_marginTop="@dimen/dimen_110_dp" ეს დაშორება არ გამოიყენო. გამოიყენე constraint chain vertical, რომ ვიუები მიაჯაჭვოს და ცენტრში მოათავსოს პროპორციულად

2023-07-26 10:31 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/presentation/home/custom_view/SearchAndFilterView.kt
> +        if (binding.searchEditText.text?.isEmpty() == true){
yes, done

2023-07-26 10:33 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/presentation/home/custom_view/SearchAndFilterView.kt
> +        }
done

2023-07-26 10:36 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/presentation/home/ui/HomeFragment.kt
> +                handleData(true)
46-ე და 50-ე ხაზებზე ვიყენებ, რომ თუ ცარიელი არ არის API-დან მომავალი ლისტი, მაშინ დაუსეტოს ადაპტერს. თუ ცარიელი მოვა, მაშინ False არის და მაგიტომ მჭირდება ბულიანი

2023-07-26 10:40 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/error_custom_view.xml
>          android:layout_marginTop="@dimen/dimen_110_dp"
ჩეინის შემთხვევაშიც მარჯინი ტოპია და მის გარეშე ზედა ვიუს მიედება. ბოთომი რომ იყოს კი ბატონო, მაგრამ რიფრეშის ღილაკი დიდი დაშორებით უნდა იყოს

2023-07-26 10:53 UTC, DavitTsiskarashvili commented on app/src/main/java/com/movies/data/remote/mapper/MovieListDTOMapper.kt
> +
done

2023-07-26 11:01 UTC, AnaRusadze approved these changes

2023-07-26 11:02 UTC, AnaRusadze commented
ერთი ეფრუვი და ჩავმერჯავ

2023-07-26 11:14 UTC, Gio481 approved these changes

2023-07-26 11:25 UTC, merged